### ISSUE TITLE
Demo contains multiple roles with the same name #1191

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-b2b-extensions#4]
Version info: 
- Browser version: 
- Platform version:
- Module version: 

### Expected behavior
Should only have one "Corporate Manager" etc.
### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/32020590-8b6bbd8c-b985-11e7-8197-1148ad41bee8.png)

**Comment by asvishnyakov** [comment]
Not actual after latest changes related to B2B functionality
