### ISSUE TITLE
Rename repository and solution to have more consistent name with the functionality of the module

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-module-b2b-extensions#5]
As far as the module will only extend customer model/functionality I would suggest to rename repository, solution, namespaces, package to something like
**vc-module-b2b-customer**
so it would be consistent with standard
vc-module-customer
module.

@Woland2k, @IgorisB please confirm or suggest another module naming.

**Comment by Woland2k** [comment]
@aartiomov vc-module-b2b-customer is a good name, you can rename it

**Comment by eMazeika** [comment]
new repository vc-module-b2b-customer created for developing only customer related features
