### ISSUE TITLE
Create vc-module-b2b-customer repository

### ISSUE THREAD

**Issue by aartiomov** [VirtoCommerce/vc-module-b2b-extensions#8]
Create vc-module-b2b-customer repository.
Create VirtoCommerce.B2BCustomerModule solution.
Migrate B2B customer related functionality to the new module.
Separate solution into projects by responsibility - Core, Data, Web.

**Comment by asvishnyakov** [comment]
Hey! You can just rename old repository

**Comment by aartiomov** [comment]
We will move only customer related extensions to the new repository/module and will leave the email notification in this module.
